# Generated by Django 5.2.7 on 2025-11-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_progress_option_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.chapter'),
        ),
    ]
