# Generated by Django 5.2.7 on 2025-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_chapter_options_alter_chapter_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
