# Generated by Django 5.2.7 on 2025-11-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_quiz_options_quiz_is_required_quiz_order_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video_url',
        ),
    ]
