# Generated by Django 5.2.7 on 2025-11-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_category_course_category_obj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['answered_at']},
        ),
        migrations.AlterModelOptions(
            name='topicprogress',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'Topic Progress', 'verbose_name_plural': 'Topic Progress Records'},
        ),
    ]
