# Generated by Django 5.2.7 on 2025-11-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_model_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
